config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post "photos/:id" => "photos#update", :as => :create_comment
  # Defines the root path route ("/")
  root "photos#index"
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comments
  has_one_attached :image
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show update edit destroy ]
  before_action :authenticate_user!, except: [:index, :show]

#  before_action only: [:update, :show] do
#    authorize_request(["normal_user", "admin"])
#  end
  before_action only: [:new, :edit, :create, :destroy] do
        authorize_request(["admin"])
  end

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
    @comments = Comment.all
    @user = User.new
  end

  # GET /photos/1 or /photos/1.json
  def show
    @comment = Comment.new
#    @photo.comments.build
  end

  # GET /photos/new
  def new
    @photo = Photo.new
#    @photo.comments.build
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)
    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    if params[:photo]   # Para caso de modificar foto (Solo Karina)
      respond_to do |format|
        if @photo.update(photo_params)
          format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
          format.json { render :show, status: :ok, location: @photo }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      end
    elsif params[:comment]  # Para agregar comentario a Fotos (Todos los usuarios registrados)
      @comment = Comment.new
      @comment.user_id = current_user.id
      @comment.photo_id = @photo.id
      @comment.post = params[:comment][:post]
      respond_to do |format|
        if @comment.save!
          format.html { redirect_to photos_path, notice: "Comment was successfully added." }
          format.json { render :show, status: :ok, location: @photo }
        else
          format.html { render :show, status: :unprocessable_entity }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      end
    end

    
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:id, :image, :legend)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image, multiple: false, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :legend, style: "display: block" %>
    <%= form.text_area :legend, autocomplete: "comentario", :cols => 80, :rows=> 3%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">

<br>
    <div class="card">
      <%= link_to(image_tag(photo.image, width: "100%"), photo.image, class: "card-img-top") %>
      <div class="card-body">
        <p class="card-text"><%= photo.legend %></p>
      </div>
    </div>

</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Photos</h1>

<div id="photos">
  <% @photos.each do |photo| %>
   <div class="container row">
    <div class="col-sm-6">
      <%= render photo %>
      <p><%= link_to "Show this photo", photo %></p>
    </div>
<%#  ### Columna de Comentarios ###  %>
    <div class="col-sm-6" style= "max-height:250px">
      <p><strong>Comentarios:</strong></p>
      <div class="form-floating postComments">
        <% photo.comments.each do |comment| %>
          <%= image_tag(comment.user.photo, height: "20px") %>
          <span style= "font-size: 1.2vw"><%#= comment.user.name %></span> - <span style= "font-size: 1.5vw"><%= comment.post %></span><br>
        <% end %>
      </div>
    </div>
   </div>
  <% end %>
</div>

<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container row">
  <div class="col-sm-6">
    <%= render @photo %>
  </div>

          <%#  ###Ingreso de Comentarios a las Fotos###  %>
  <div class="col-sm-6" style= "max-height:250px">
    <%#= form_with(model: @photo, url: photo_path, method: :get) do |form| %>
    <%#= form_with model: @photo, method: :post do |photo_form| %>
      <%#= photo_form.hidden_field :id, value: @photo.id %>
      <div>
      <%= form_with model: @comment, url: photo_path, method: :post  do |comment_form| %>
        <%= comment_form.text_area :post, :cols => 50, :rows => 3 %>
      <%# end %>
        <%#= form.label "Ingresa tu Comentario", style: "display: block" %>
        <%#= form.text_area @comentario, :cols => 50, :rows => 3 %>
      </div>
      <div>
        <%= comment_form.submit "Enviar" %>
      </div>
      <% end %>
    <%# end %>
  </div>
          <%#   #######################################  %>
</div>
<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>